# General
theme: jekyll-theme-cayman
title: Quant_Toolbox
description: Full stack toolbox for a child quant.
nav:
- name: Home
  link: https://jhqian0909.github.io/Quant_Toolbox/
- name: Xue Qiu
  link: https://xueqiu.com/u/1667547355
- name: Blogs
  link: https://jhqian0909.github.io/Quant_Toolbox/blogs_home/index.html
  
sass:
  sass_dir: assets/css
future: true


# Pagination
paginate:           7
paginate_path:     "/blogs_home/page:num/"
plugins:
  - jekyll-paginate
