# General
theme: jekyll-theme-cayman
title: Quant_Toolbox
description: Full stack toolbox for a child quant.
nav:
- name: Home
  link: https://jhqian0909.github.io/Quant_Toolbox/
- name: IA DAP
  link: https://ui-oa-dap-zyuan-air9-jpr.dlmtprd-apps.dlk-prd.us-east-1.ac.discoverfinancial.com/
- name: Blog
  link: https://github.discoverfinancial.com/pages/zyuan/IA_Data_Analytics_Platform/blogs_home/index.html
  
sass:
  sass_dir: assets/css
future: true


# Pagination
paginate:           7
paginate_path:     "/blogs_home/page:num/"
plugins:
  - jekyll-paginate
